//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDousCOrd
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOU
    {
        public long DOU_id { get; set; }
        public Nullable<long> DOU_number { get; set; }
        public string DOU_Name { get; set; }
        public string DOU_ShortName { get; set; }
        public long Street_id { get; set; }
        public long DOU_House { get; set; }
        public string DOU_Building { get; set; }
        public long Microdistrict_id { get; set; }
        public string DOU_Phones { get; set; }
        public string DOU_DirectorFIO { get; set; }
        public string DOU_Email { get; set; }
        public string DOU_Url { get; set; }
        public string DOU_DeputyDirectorFIO { get; set; }
        public Nullable<long> DOUForm_id { get; set; }
        public Nullable<long> DOUType_id { get; set; }
        public Nullable<long> DOUCategory_id { get; set; }
        public Nullable<bool> DOU_IsCommercial { get; set; }
        public Nullable<bool> DOU_IsVisible { get; set; }
        public string DOU_DirectorLastName { get; set; }
        public string DOU_DirectorFirstName { get; set; }
        public string DOU_DirectorPatronymicName { get; set; }
        public Nullable<long> DOU_oldid { get; set; }
        public Nullable<long> Holding_id { get; set; }
        public Nullable<long> CompSpec_id { get; set; }
        public Nullable<long> HealthSpec_id { get; set; }
        public Nullable<System.DateTime> System_insDT { get; set; }
        public Nullable<long> System_insAccount { get; set; }
        public Nullable<System.DateTime> System_updDT { get; set; }
        public Nullable<long> System_updAccount { get; set; }
        public Nullable<long> DOU_Fax { get; set; }
        public Nullable<int> DOUOPForm_id { get; set; }
        public Nullable<int> DOUBuildType_id { get; set; }
        public Nullable<int> DOUOwnForm_id { get; set; }
        public Nullable<int> DOUBuilWear { get; set; }
        public string DOU_WorkTime { get; set; }
        public string DOU_MealType { get; set; }
        public string DOU_AdditionalEducation { get; set; }
        public string DOU_Features { get; set; }
        public string DOU_OwnerName { get; set; }
        public Nullable<int> OwnerType_id { get; set; }
        public Nullable<bool> DOU_License { get; set; }
        public string DOU_Cords { get; set; }
    
        public virtual Street Street { get; set; }
    }
}
