//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDousCOrd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Street
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Street()
        {
            this.DOUs = new HashSet<DOU>();
        }
    
        public long Street_id { get; set; }
        public string Street_name { get; set; }
        public Nullable<System.DateTime> System_insDT { get; set; }
        public Nullable<long> System_insAccount { get; set; }
        public Nullable<System.DateTime> System_updDT { get; set; }
        public Nullable<long> System_updAccount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOU> DOUs { get; set; }
    }
}
